### Notes
#
# - some environment variables are needed to make sure this docker-compose config file works
#
version: '2'

services:
    stdiscosrv:
        build: images/stdiscosrv
        hostname: stdiscosrv
        container_name: stdiscosrv
        ports:
            - "8443:8443"
        volumes:
            - ./config/stdiscosrv:/opt/stdiscosrv/etc
            - ./data/stdiscosrv:/opt/stdiscosrv/var
        environment:
            - CONTAINER_NAME=stdiscosrv
            - CONTAINER_USER=run
            - LOCAL_GID=1000
            - LOCAL_UID=1000
        command: 'stdiscosrv -cert /opt/stdiscosrv/etc/cert.pem -key /opt/stdiscosrv/etc/key.pem -limit-avg 10 -limit-cache 25000 -stats-file /opt/stdiscosrv/var/stats -db-dsn file:///opt/stdiscosrv/var/stdiscosrv.db'
        restart: always

    strelaysrv:
        build: images/strelaysrv
        hostname: strelaysrv
        container_name: strelaysrv
        ports:
            - "443:22067"
            - "22070:22070"
        volumes:
            - ./config/strelaysrv:/opt/strelaysrv/etc
        environment:
            - CONTAINER_NAME=strelaysrv
            - CONTAINER_USER=run
            - LOCAL_GID=1000
            - LOCAL_UID=1000
        command: 'strelaysrv -keys /opt/strelaysrv/etc -debug -ext-address=":443" -listen=":22067" -status-srv=":22070" -pools="" -provided-by="Banovo GmbH"'
        restart: always
