### Notes
#
# - some environment variables are needed to make sure this docker-compose config file works
#
version: '2'

services:
    stdiscosrv:
        build: 'images/stdiscosrv'
        hostname: stdiscosrv
        container_name: stdiscosrv
        ports:
            - '8443:8443'
        volumes:
            - './config/stdiscosrv:/opt/stdiscosrv/etc'
            - './data/stdiscosrv:/opt/stdiscosrv/var'
        environment:
            - CONTAINER_NAME=stdiscosrv
        env_file:
            - docker-compose.env
            - docker-compose.local.env
        command: 'stdiscosrv -cert /opt/stdiscosrv/etc/cert.pem -key /opt/stdiscosrv/etc/key.pem -limit-avg 10 -limit-cache 25000 -stats-file /opt/stdiscosrv/var/stats -db-dsn file:///opt/stdiscosrv/var/stdiscosrv.db'
        restart: always

    strelaysrv:
        build: 'images/strelaysrv'
        hostname: strelaysrv
        container_name: strelaysrv
        ports:
            - '443:22067'
            - '22070:22070'
        volumes:
            - './config/strelaysrv:/opt/strelaysrv/etc'
        environment:
            - CONTAINER_NAME=strelaysrv
        env_file:
            - docker-compose.env
            - docker-compose.local.env
        command: 'strelaysrv -keys /opt/strelaysrv/etc -ext-address=":443" -listen=":22067" -status-srv=":22070" -pools="" -provided-by="Banovo GmbH"'
        restart: always

    syncthing:
        build: 'images/syncthing'
        hostname: syncthing
        container_name: syncthing
        ports:
            - '8384:8384'
            - '22000:22000'
            - '21027:21027/udp'
        volumes:
            - './config/syncthing:/opt/syncthing/etc'
            - './data/syncthing:/opt/syncthing/var'
        environment:
            - CONTAINER_NAME=syncthing
        env_file:
            - docker-compose.env
            - docker-compose.local.env
        command: 'syncthing -home=/opt/syncthing/etc'
        restart: always
